name:                HsPDF
version:             0.1.0.0
license:             BSD3
author:              uuhan
category:            PDF
build-tools:         c2hs
custom-setup:
  dependencies:
    - base
    - directory
    - Cabal
extra-source-files:
  - README.md
extra-libraries:
  - hpdfs
  - png
  - z

include-dirs:
  - libharu/include
  - include

c-sources:
  - cbits/utils.c

when:
  - condition: os(darwin)
    cc-options: -U__BLOCKS__ -D_Nonnull=

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Graphics.PDF.LibHaru.Types
    - Graphics.PDF.LibHaru.Consts
    - Graphics.PDF.LibHaru.Objects
    - Graphics.PDF.LibHaru.Font
    - Graphics.PDF.LibHaru.Doc
    - Graphics.PDF.LibHaru.Page
    - Graphics.PDF.LibHaru.Utils
    - Graphics.PDF.LibHaru

executables:
  HsPDF: &main
    source-dirs:
      - .
      - demo
    main: Main.hs
    ghc-options: -O2 -threaded
    dependencies:
      - HsPDF
      - parsec

  image_demo:
    <<: *main
    main: image_demo.hs

  arc_demo:
    <<: *main
    main: arc_demo.hs

  attach:
    <<: *main
    main: attach.hs
