name:                HsPDF
version:             0.1.0.0
license:             BSD3
author:              uuhan
category:            PDF
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  HsPDF:
    source-dirs:      src
    main:             Main.hs
