name:                HsPDF
version:             0.1.0.0
license:             BSD3
author:              uuhan
category:            PDF
custom-setup:
  dependencies:
    - base
    - directory
    - Cabal
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Graphics.PDF.LibHaru

executables:
  HsPDF:
    source-dirs:      .
    main:             Main.hs
    dependencies:
      - HsPDF
